In [ ]:
'''
Group by
Aggregate Functions -> (mean, max, min, count, sum)
Order by -> sort_values(ascending=True/False, by=column_name, ignore_index=True/False (default))
rename -> dictionary {'current_column_name':'replaced_column_name'}
agg -> for analysis of multiple aggregate function columns
'''

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('hr_cleaned_data.csv')

In [7]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName,M_first_name,M_middle_name,M_last_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Low Salary,0,0,0,Wilson,K,Adinolfi,Michael,NaN,Albert
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Medium Salary,1,1,1,Karthikeyan,NaN,Ait Sidi,Simon,NaN,Roup
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Low Salary,0,1,0,Sarah,NaN,Akinkuolie,Kissy,NaN,Sullivan
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Low Salary,0,1,1,Trina,NaN,Alagbe,Elijiah,NaN,Gray
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Low Salary,0,1,1,Carol,NaN,Anderson,Webster,NaN,Butler

In [8]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'HireYear', 'HireMonth', 'HireDay', 'HireMonth_Name',
       'HireDay_Name', 'Salary_Label', 'salary_label_num',
       'PerformanceScore_id', 'HireDay_Name_id', 'E_FirstName', 'E_MiddleName',
       'E_LastName', 'M_first_name', 'M_middle_name', 'M_last_name'],
      dtype='object')

In [ ]:
# Find total employees hired through each Recruitment Source.
'''
    Syntax
    -------
    -> dataframe.groupby(column_name)[column_name].agg_function()
'''
# df['RecruitmentSource'].unique()

In [13]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count()

In [14]:
emp_recruitement

RecruitmentSource
CareerBuilder               23
Diversity Job Fair          61
Employee Referral           61
Google Search               82
Indeed                     146
LinkedIn                   192
On-line Web application      2
Other                        2
Website                     13
Name: EmpID, dtype: int64

In [24]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees', 'RecruitmentSource': 'Recruitment Source'}
).sort_values(ascending=False, by='Total Employees', ignore_index=True)
emp_recruitement.tail()

        Recruitment Source  Total Employees
4        Employee Referral               61
5            CareerBuilder               23
6                  Website               13
7  On-line Web application                2
8                    Other                2

In [42]:
emp_recruitement = df.groupby('RecruitmentSource')['EmpID'].count().rename('Total Employees').rename_axis('Recruitment Source')
format_data = emp_recruitement.to_markdown(numalign='center', stralign='center')

In [43]:
print(format_data)

|   Recruitment Source    |  Total Employees  |
|:-----------------------:|:-----------------:|
|      CareerBuilder      |        23         |
|   Diversity Job Fair    |        61         |
|    Employee Referral    |        61         |
|      Google Search      |        82         |
|         Indeed          |        146        |
|        LinkedIn         |        192        |
| On-line Web application |         2         |
|          Other          |         2         |
|         Website         |        13         |

In [57]:
# Find total employees hired through each Recruitment Source and Gender.
recruitment_gender = df.groupby(['RecruitmentSource', 'Gender'])['EmpID'].count().reset_index().rename(
    columns = {'RecruitmentSource': 'Recruitment Source', 'EmpID':'Total Employees'}
)
recruitment_gender

         Recruitment Source Gender  Total Employees
0             CareerBuilder      F               16
1             CareerBuilder      M                7
2        Diversity Job Fair      F               45
3        Diversity Job Fair      M               16
4         Employee Referral      F               12
5         Employee Referral      M               49
6             Google Search      F               64
7             Google Search      M               18
8                    Indeed      F               79
9                    Indeed      M               67
10                 LinkedIn      F              131
11                 LinkedIn      M               61
12  On-line Web application      M                2
13                    Other      F                1
14                    Other      M                1
15                  Website      F                6
16                  Website      M                7

In [67]:
def changeCurrency(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)

In [70]:
# Find total employees hired and total salary distribution of employees by each Recruitment Source and Gender.
rec_gen_sal = df.groupby(['RecruitmentSource', 'Gender']).agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary', 'sum'),
    Max_Salary = ('Salary', 'max'),
    Min_Salary = ('Salary', 'min')
).reset_index()
# rec_gen_sal['Total_Salary'] = rec_gen_sal['Total_Salary'].map('${:,.2f}'.format)
changeCurrency(rec_gen_sal, 'Rs.', 'Total_Salary', 'Max_Salary', 'Min_Salary')
rec_gen_sal

,RecruitmentSource,Gender,Total_Employees,Total_Salary,Max_Salary,Min_Salary
0,CareerBuilder,F,16,"Rs.989,848.00","Rs.101,199.00","Rs.46,335.00"
1,CareerBuilder,M,7,"Rs.470,250.00","Rs.93,046.00","Rs.46,837.00"
2,Diversity Job Fair,F,45,"Rs.3,202,621.00","Rs.650,000.00","Rs.47,434.00"
3,Diversity Job Fair,M,16,"Rs.1,328,473.00","Rs.157,000.00","Rs.47,211.00"
4,Employee Referral,F,12,"Rs.1,040,301.00","Rs.220,450.00","Rs.45,069.00"
5,Employee Referral,M,49,"Rs.4,046,433.00","Rs.500,000.00","Rs.46,664.00"
6,Google Search,F,64,"Rs.4,124,312.00","Rs.500,825.00","Rs.45,433.00"
7,Google Search,M,18,"Rs.1,061,679.00","Rs.77,692.00","Rs.46,428.00"
8,Indeed,F,79,"Rs.5,511,116.00","Rs.250,000.00","Rs.46,430.00"
9,Indeed,M,67,"Rs.6,020,604.00","Rs.178,000.00","Rs.50,178.00"
10,LinkedIn,F,131,"Rs.9,825,058.00","Rs.650,000.00","Rs.45,046.00"
11,LinkedIn,M,61,"Rs.3,801,915.00","Rs.103,613.00","Rs.45,115.00"
12,On-line Web application,M,2,"Rs.105,010.00","Rs.52,505.00","Rs.52,505.00"
13,Other,F,1,"Rs.99,351.00","Rs.99,351.00","Rs.99,351.00"
14,Other,M,1,"Rs.67,176.00","Rs.67,176.00","Rs.67,176.00"
15,Website,F,6,"Rs.363,594.00","Rs.77,915.00","Rs.51,920.00"
16,Website,M,7,"Rs.436,396.00","Rs.70,468.00","Rs.55,140.00"

In [63]:
rec_gen_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RecruitmentSource  17 non-null     object
 1   Gender             17 non-null     object
 2   Total_Employees    17 non-null     int64
 3   Total_Salary       17 non-null     int64
 4   Max_Salary         17 non-null     int64
 5   Min_Salary         17 non-null     int64
dtypes: int64(4), object(2)
memory usage: 948.0+ bytes