In [26]:
import pandas as pd

In [27]:
df = pd.read_csv('hr_cleaned_data.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   582 non-null    int64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(1), int64(17), object(18)
memory usage: 163.8+ KB

In [29]:
def changeDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [30]:
changeDateTime(df, 'DateofTermination', 'DOB', 'DateofHire', 'LastPerformanceReview_Date')

### Extract Year, Month, Day

In [31]:
'''
year
month / month_name()
day / day_name()
'''
# dataframe['new_col'] = dataframe[col].dt.year/month/day

'\nyear\nmonth / month_name()\nday / day_name()\n'

In [32]:
df['HireYear'] = df['DateofHire'].dt.year

In [33]:
df['HireMonth'] = df['DateofHire'].dt.month
df['HireDay'] = df['DateofHire'].dt.day

In [34]:
## Extract date name
df['HireMonth_Name'] = df['DateofHire'].dt.month_name()
df['HireDay_Name'] = df['DateofHire'].dt.day_name()

### Convert Continuous data to Categorical data

In [35]:
def convertSalary(salary):
    if salary > 0 and salary <= 70000:
        return 'Low Salary'
    elif salary > 70000 and salary <= 150000:
        return 'Medium Salary'
    else:
        return 'High Salary'

In [36]:
# apply
df['Salary_Label'] = df['Salary'].apply(convertSalary)

### Feature Encoding

In [37]:
'''
- Manual Encoding
    Dictionary
- Use map() function
    -> dataframe[col_name] = dataframe[col_name].map(dict)
'''

'\n- Manual Encoding\n    Dictionary\n- Use map() function\n    -> dataframe[col_name] = dataframe[col_name].map(dict)\n'

In [38]:
df['Salary_Label'].unique()

array(['Low Salary', 'Medium Salary', 'High Salary'], dtype=object)

In [39]:
# Label Encoder
#     High Salary - 0 
#     Low Salary - 1
#     Medium Salary - 2

In [40]:
salary_dict = {
    'Low Salary': 0,
    'Medium Salary': 1,
    'High Salary': 2
}

In [41]:
df['salary_label_num'] = df.loc[:,'Salary_Label'].map(salary_dict)

In [42]:
def manualEncode(dataframe, col_name, *args):
    encode_value = {}
    for idx, val in enumerate(args):
        encode_value[val] = idx

    dataframe[f'{col_name}_id'] = dataframe[col_name].map(encode_value)

In [43]:
manualEncode(df, 'PerformanceScore', 'Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP')

In [44]:
manualEncode(df, 'HireDay_Name', 'Tuesday', 'Monday', 'Thursday', 'Wednesday', 'Sunday', 'Friday','Saturday')

In [45]:
df['ManagerName'].unique()

array(['Michael Albert', 'Simon Roup', 'Kissy Sullivan', 'Elijiah Gray',
       'Webster Butler', 'Amy Dunn', 'Alex Sweetwater', 'Ketsia Liebig',
       'Brannon Miller', 'Peter Monroe', 'David Stanley', 'Kelley Spirea',
       'Brandon R. LeBlanc', 'Janet King', 'John Smith',
       'Jennifer Zamora', 'Lynn Daneault', 'Eric Dougall',
       'Debra Houlihan', 'Brian Champaigne', 'Board of Directors'],
      dtype=object)

### Split Columns

In [46]:
'''
- Use of Split
------------------
- To separate data into multiple columns on the basis of common character.
- df['col_name'].str.split(find, n(no._of_columns)=index, expand=True/False(default))
'''

"\n- Use of Split\n------------------\n- To separate data into multiple columns on the basis of common character.\n- df['col_name'].str.split(find, n(no._of_columns)=index, expand=True/False(default))\n"

In [47]:
df['Salary_Label'].unique()

array(['Low Salary', 'Medium Salary', 'High Salary'], dtype=object)

In [48]:
salary_columns = df['Salary_Label'].str.split(' ', n=1, expand=True)
salary_columns.head()

        0       1
0     Low  Salary
1  Medium  Salary
2     Low  Salary
3     Low  Salary
4     Low  Salary

In [49]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [50]:
emp_name = hr['Employee_Name'].str.split(',', n=1, expand=True)
# emp_name.head()

In [51]:
first_middle = emp_name[1].str.strip().str.split(' ', n=1, expand=True)
# first_middle.head()

In [52]:
df['E_FirstName'] = first_middle[0]
df['E_MiddleName'] = first_middle[1]
df['E_LastName'] = emp_name[0]

In [53]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,HireDay,HireMonth_Name,HireDay_Name,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,5,July,Tuesday,Low Salary,0,0,0,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,30,March,Monday,Medium Salary,1,1,1,Karthikeyan,None,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,5,July,Tuesday,Low Salary,0,1,0,Sarah,None,Akinkuolie
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,7,January,Monday,Low Salary,0,1,1,Trina,None,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,Low Salary,0,1,1,Carol,None,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,Low Salary,0,1,1,Carol,None,Anderson
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,9,January,Monday,Low Salary,0,0,1,Linda,None,Anderson
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,10,November,Monday,Medium Salary,1,1,1,Colby,None,Andreola
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,30,September,Monday,Low Salary,0,1,1,Sam,None,Athwal
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,6,July,Monday,Low Salary,0,1,1,Linda,None,Bachiochi

In [54]:
'''
- StandardScaler
- Label Encoder
- One Hot Encoder
- Min Max Scaler
- Robust Scaler
'''

'\n- StandardScaler\n- Label Encoder\n- One Hot Encoder\n- Min Max Scaler\n- Robust Scaler\n'

In [69]:
import numpy as np
# Michael Albert

In [70]:
def splitName(name):
    value = name.strip().split() # ['Michael', 'middle', 'Albert']

    if len(value) == 1:
        return pd.Series([value[0], np.nan, np.nan])
    elif len(value) == 2:
        return pd.Series([value[0], np.nan, value[1]])
    else:
        return pd.Series([value[0], value[1], value[2]])

In [65]:
df[['M_first_name', 'M_middle_name', 'M_last_name']] = df['ManagerName'].apply(splitName)

In [68]:
df[df['ManagerName'] == 'Brandon R. LeBlanc']

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName,M_first_name,M_middle_name,M_last_name
45,Boutwell Bonalyn,10081,1,1,0,1,1,3,1,106367,...,Medium Salary,1,1,1,Bonalyn,None,Boutwell,Brandon,R.,LeBlanc
48,Brown Mia,10238,1,1,0,1,1,3,1,63000,...,Low Salary,0,1,1,Mia,None,Brown,Brandon,R.,LeBlanc
151,Howard Estelle,10182,1,1,0,1,1,3,0,49920,...,Low Salary,0,1,1,Estelle,None,Howard,Brandon,R.,LeBlanc
179,LaRotonda William,10038,0,2,1,1,1,3,0,64520,...,Low Salary,0,1,1,William,None,LaRotonda,Brandon,R.,LeBlanc
274,Singh Nan,10039,0,0,0,1,1,3,0,51920,...,Low Salary,0,1,5,Nan,None,Singh,Brandon,R.,LeBlanc
278,Smith Leigh Ann,10153,1,1,0,5,1,3,1,55000,...,Low Salary,0,1,1,Leigh,Ann,Smith,Brandon,R.,LeBlanc
287,Steans Tyrone,10147,0,0,1,1,1,3,0,63003,...,Low Salary,0,1,1,Tyrone,None,Steans,Brandon,R.,LeBlanc

In [66]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName,M_first_name,M_middle_name,M_last_name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Low Salary,0,0,0,Wilson,K,Adinolfi,Michael,NaN,Albert
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Medium Salary,1,1,1,Karthikeyan,None,Ait Sidi,Simon,NaN,Roup
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Low Salary,0,1,0,Sarah,None,Akinkuolie,Kissy,NaN,Sullivan
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Low Salary,0,1,1,Trina,None,Alagbe,Elijiah,NaN,Gray
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Low Salary,0,1,1,Carol,None,Anderson,Webster,NaN,Butler
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Low Salary,0,1,1,Carol,None,Anderson,Webster,NaN,Butler
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Low Salary,0,0,1,Linda,None,Anderson,Amy,NaN,Dunn
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Medium Salary,1,1,1,Colby,None,Andreola,Alex,NaN,Sweetwater
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Low Salary,0,1,1,Sam,None,Athwal,Ketsia,NaN,Liebig
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Low Salary,0,1,1,Linda,None,Bachiochi,Brannon,NaN,Miller

In [74]:
df.to_csv('hr_cleaned_data.csv', index=False)