In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('hr_cleaned_data.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2

In [ ]:
df.info()

In [ ]:
def changeDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')

In [ ]:
changeDateTime(df, 'DateofTermination', 'DOB', 'DateofHire', 'LastPerformanceReview_Date')

### Extract Year, Month, Day

In [ ]:
'''
year
month / month_name()
day / day_name()
'''
# dataframe['new_col'] = dataframe[col].dt.year/month/day

'\nyear\nmonth / month_name()\nday / day_name()\n'

In [ ]:
df['HireYear'] = df['DateofHire'].dt.year

In [ ]:
df['HireMonth'] = df['DateofHire'].dt.month
df['HireDay'] = df['DateofHire'].dt.day

In [ ]:
## Extract date name
df['HireMonth_Name'] = df['DateofHire'].dt.month_name()
df['HireDay_Name'] = df['DateofHire'].dt.day_name()

### Convert Continuous data to Categorical data

In [ ]:
def convertSalary(salary):
    if salary > 0 and salary <= 70000:
        return 'Low Salary'
    elif salary > 70000 and salary <= 150000:
        return 'Medium Salary'
    else:
        return 'High Salary'

In [ ]:
# apply
df['Salary_Label'] = df['Salary'].apply(convertSalary)

### Feature Encoding

In [ ]:
'''
- Manual Encoding
    Dictionary
- Use map() function
    -> dataframe[col_name] = dataframe[col_name].map(dict)
'''

'\n- Manual Encoding\n    Dictionary\n- Use map() function\n    -> dataframe[col_name] = dataframe[col_name].map(dict)\n'

In [ ]:
df['Salary_Label'].unique()

array(['Low Salary', 'Medium Salary', 'High Salary'], dtype=object)

In [ ]:
# Label Encoder
#     High Salary - 0 
#     Low Salary - 1
#     Medium Salary - 2

In [ ]:
salary_dict = {
    'Low Salary': 0,
    'Medium Salary': 1,
    'High Salary': 2
}

In [ ]:
df['salary_label_num'] = df.loc[:,'Salary_Label'].map(salary_dict)

In [ ]:
def manualEncode(dataframe, col_name, *args):
    encode_value = {}
    for idx, val in enumerate(args):
        encode_value[val] = idx

    dataframe[f'{col_name}_id'] = dataframe[col_name].map(encode_value)

In [ ]:
manualEncode(df, 'PerformanceScore', 'Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP')

In [ ]:
manualEncode(df, 'HireDay_Name', 'Tuesday', 'Monday', 'Thursday', 'Wednesday', 'Sunday', 'Friday','Saturday')

In [ ]:
df['ManagerName'].unique()

array(['Michael Albert', 'Simon Roup', 'Kissy Sullivan', 'Elijiah Gray',
       'Webster Butler', 'Amy Dunn', 'Alex Sweetwater', 'Ketsia Liebig',
       'Brannon Miller', 'Peter Monroe', 'David Stanley', 'Kelley Spirea',
       'Brandon R. LeBlanc', 'Janet King', 'John Smith',
       'Jennifer Zamora', 'Lynn Daneault', 'Eric Dougall',
       'Debra Houlihan', 'Brian Champaigne', 'Board of Directors'],
      dtype=object)

### Split Columns

In [ ]:
'''
- Use of Split
------------------
- To separate data into multiple columns on the basis of common character.
- df['col_name'].str.split(find, n(no._of_columns)=index, expand=True/False(default))
'''

"\n- Use of Split\n------------------\n- To separate data into multiple columns on the basis of common character.\n- df['col_name'].str.split(find, n(no._of_columns)=index, expand=True/False(default))\n"

In [ ]:
df['Salary_Label'].unique()

array(['Low Salary', 'Medium Salary', 'High Salary'], dtype=object)

In [ ]:
salary_columns = df['Salary_Label'].str.split(' ', n=1, expand=True)
salary_columns.head()

        0       1
0     Low  Salary
1  Medium  Salary
2     Low  Salary
3     Low  Salary
4     Low  Salary

In [ ]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
hr.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [165]:
emp_name = hr['Employee_Name'].str.split(',', n=1, expand=True)
# emp_name.head()

In [166]:
first_middle = emp_name[1].str.strip().str.split(' ', n=1, expand=True)
# first_middle.head()

In [163]:
df['E_FirstName'] = first_middle[0]
df['E_MiddleName'] = first_middle[1]
df['E_LastName'] = emp_name[0]

In [164]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,HireDay,HireMonth_Name,HireDay_Name,Salary_Label,salary_label_num,PerformanceScore_id,HireDay_Name_id,E_FirstName,E_MiddleName,E_LastName
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,5,July,Tuesday,Low Salary,0,0,0,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,30,March,Monday,Medium Salary,1,1,1,Karthikeyan,None,Ait Sidi
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,5,July,Tuesday,Low Salary,0,1,0,Sarah,None,Akinkuolie
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,7,January,Monday,Low Salary,0,1,1,Trina,None,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,Low Salary,0,1,1,Carol,None,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,11,July,Monday,Low Salary,0,1,1,Carol,None,Anderson
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,9,January,Monday,Low Salary,0,0,1,Linda,None,Anderson
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,10,November,Monday,Medium Salary,1,1,1,Colby,None,Andreola
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,30,September,Monday,Low Salary,0,1,1,Sam,None,Athwal
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,6,July,Monday,Low Salary,0,1,1,Linda,None,Bachiochi

In [ ]:
'''
- StandardScaler
- Label Encoder
- One Hot Encoder
- Min Max Scaler
- Robust Scaler
'''