In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Dataset/financial_loan_data.xlsx')
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  datetime64[ns]
 8   last_credit_pull_date  38576 non-null  datetime64[ns]
 9   last_payment_date      38576 non-null  datetime64[ns]
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  datetime64[ns]
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(5), object(11)
memory usage: 7.1+ MB

In [4]:
df.isnull().sum()

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

#### Fill custom record in employee title column

In [5]:
df.fillna({'emp_title': 'Unknown Title'}, inplace=True)

#### Separate Month from Data

In [6]:
df['Issue_Month'] = df['issue_date'].dt.month
df['I_month_name'] = df['issue_date'].dt.month_name()

In [ ]:
'''
Growth Percentage
===================
current_value -> Current Month Value -> MTD (Month to Date)
baseline_value -> Previous Month Value -> PMTD (Previous Month to Date)

MoM (Month over Month) = ((current_value - baseline_value)/baseline_value)*100
'''

In [7]:
current_month = 12
previous_month = 11

## KPIs

### Total Loan Applicants

In [8]:
total_applicants = df['id'].count()
# MTD_total_applicants = df[df.loc[:,'Issue_Month'] == 12]['id'].count()
MTD_total_applicants = df[df['Issue_Month'] == 12]['id'].count()
PMTD_total_applicants = df[df['Issue_Month'] == 11]['id'].count()
MoM_total_applicants = round(((MTD_total_applicants - PMTD_total_applicants) / PMTD_total_applicants)*100, 2)

In [9]:
print(f'Total Applicants: {total_applicants}')
print(f'MTD Total Applicants: {MTD_total_applicants}')
print(f'PMTD Total Applicants: {PMTD_total_applicants}')
print(f'MoM Total Applicants: {MoM_total_applicants}%')

Total Applicants: 38576
MTD Total Applicants: 4314
PMTD Total Applicants: 4035
MoM Total Applicants: 6.91%

### Total Funded Amount

In [10]:
funded_amount = df['loan_amount'].sum()
MTD_funded_amount = df[df['Issue_Month'] == 12]['loan_amount'].sum()
PMTD_funded_amount = df[df['Issue_Month'] == 11]['loan_amount'].sum()
MoM_funded_amount = round(((MTD_funded_amount - PMTD_funded_amount) / PMTD_funded_amount)*100, 2)

In [11]:
print(f'Funded Amount: ${funded_amount:,.2f}')
print(f'MTD Funded Amount: ${MTD_funded_amount:,.2f}')
print(f'PMTD Funded Amount: ${PMTD_funded_amount:,.2f}')
print(f'MoM Funded Amount: {MoM_funded_amount}%')

Funded Amount: $435,757,075.00
MTD Funded Amount: $53,981,425.00
PMTD Funded Amount: $47,754,825.00
MoM Funded Amount: 13.04%

### Total Received Amount

In [12]:
received_amount = df['total_payment'].sum()
MTD_received_amount = df[df['Issue_Month'] == 12]['total_payment'].sum()
PMTD_received_amount = df[df['Issue_Month'] == 11]['total_payment'].sum()
MoM_received_amount = round(((MTD_received_amount - PMTD_received_amount) / PMTD_received_amount)*100, 2)

In [13]:
print(f'Received Amount: ${received_amount:,.2f}')
print(f'MTD Received Amount: ${MTD_received_amount:,.2f}')
print(f'PMTD Received Amount: ${PMTD_received_amount:,.2f}')
print(f'MoM Received Amount: {MoM_received_amount}%')

Received Amount: $473,070,933.00
MTD Received Amount: $58,074,380.00
PMTD Received Amount: $50,132,030.00
MoM Received Amount: 15.84%

### Average Interest Rate

In [14]:
int_rate = df['int_rate'].mean()
MTD_int_rate = df[df['Issue_Month'] == 12]['int_rate'].mean()
PMTD_int_rate = df[df['Issue_Month'] == 11]['int_rate'].mean()
MoM_int_rate = round(((MTD_int_rate - PMTD_int_rate) / PMTD_int_rate)*100, 2)

In [15]:
print(f'Average Interest Rate: {int_rate:,.2f}%')
print(f'MTD Average Interest Rate: {MTD_int_rate:.2f}%') # 0.12356040797403803
print(f'PMTD Average Interest Rate: {PMTD_int_rate:,.2f}%') # 0.1194171747211896
print(f'MoM Average Interest Rate: {MoM_int_rate}%')

Average Interest Rate: 0.12%
MTD Average Interest Rate: 0.12%
PMTD Average Interest Rate: 0.12%
MoM Average Interest Rate: 3.47%

### Average Debt-to-Income Ratio

In [16]:
dti_ratio = df['dti'].mean()
MTD_dti_ratio = df[df['Issue_Month'] == 12]['dti'].mean()
PMTD_dti_ratio = df[df['Issue_Month'] == 11]['dti'].mean()
MoM_dti_ratio = round(((MTD_dti_ratio - PMTD_dti_ratio) / PMTD_dti_ratio)*100, 2)

In [17]:
print(f'Average Debt to Income Ratio: {dti_ratio:,.2f}%')
print(f'MTD Average Debt to Income Ratio: {MTD_dti_ratio:.2f}%')
print(f'PMTD Average Debt to Income Ratio: {PMTD_dti_ratio:,.2f}%')
print(f'MoM Average Debt to Income Ratio: {MoM_dti_ratio}%')

Average Debt to Income Ratio: 0.13%
MTD Average Debt to Income Ratio: 0.14%
PMTD Average Debt to Income Ratio: 0.13%
MoM Average Debt to Income Ratio: 2.73%

## Good Loan and Bad Loan Data

In [27]:
# Separate good loan and bad loan data
good_loan_df = df[df['loan_status'].isin(['Fully Paid', 'Current'])]
bad_loan_df = df[df['loan_status'] == 'Charged Off']

### Good Loan KPI

#### Total Good Loan Applicants

In [23]:
total_good_loan_applicants = good_loan_df['id'].count()
good_loan_applicants_pct = (total_good_loan_applicants/total_applicants)*100
good_loan_funded_amount = good_loan_df['loan_amount'].sum()
good_loan_received_amount = good_loan_df['total_payment'].sum()

In [26]:
print(f'Total Good Loan Applicants: {total_good_loan_applicants:,}')
print(f'Total Good Loan Applicants %: {good_loan_applicants_pct:,.2f}%')
print(f'Total Good Loan Funded Amount: ${good_loan_funded_amount:,.2f}')
print(f'Total Good Loan Received Amount: ${good_loan_received_amount:,.2f}')

Total Good Loan Applicants: 33,243
Total Good Loan Applicants %: 86.18%
Total Good Loan Funded Amount: $370,224,850.00
Total Good Loan Received Amount: $435,786,170.00

#### Total Bad Loan Applicants

In [28]:
total_bad_loan_applicants = bad_loan_df['id'].count()
bad_loan_applicants_pct = (total_bad_loan_applicants/total_applicants)*100
bad_loan_funded_amount = bad_loan_df['loan_amount'].sum()
bad_loan_received_amount = bad_loan_df['total_payment'].sum()

In [29]:
print(f'Total Bad Loan Applicants: {total_bad_loan_applicants:,}')
print(f'Total Bad Loan Applicants %: {bad_loan_applicants_pct:,.2f}%')
print(f'Total Bad Loan Funded Amount: ${bad_loan_funded_amount:,.2f}')
print(f'Total Bad Loan Received Amount: ${bad_loan_received_amount:,.2f}')

Total Bad Loan Applicants: 5,333
Total Bad Loan Applicants %: 13.82%
Total Bad Loan Funded Amount: $65,532,225.00
Total Bad Loan Received Amount: $37,284,763.00

### Loan Status Grid View

In [103]:
# Currency Converter
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)

# Percentage Converter
def pctConverter(dataframe, suffix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map('{:,.2f}'f'{suffix}'.format)

In [72]:
MTD_fund = df[df['Issue_Month'] == 12]
data = MTD_fund.groupby('loan_status')['loan_amount'].sum().reset_index()
received = MTD_fund.groupby('loan_status')['total_payment'].sum().reset_index()

In [104]:
loan_grid = df.groupby('loan_status').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Amount_Received = ('total_payment', 'sum'),
    Average_Interest_Rate = ('int_rate', 'mean'),
    Average_DTI = ('dti', 'mean')
).reset_index().rename(columns = {'loan_status': 'Loan Status'})

# Merging analyzed data columns
loan_grid['MTD_Funded_Amount'] = data['loan_amount']
loan_grid['MTD_Received_Amount'] = received['total_payment']

# replacing unwanted value in column names
loan_grid.columns = loan_grid.columns.str.replace('_', ' ', regex=False)

# using functions
currencyConverter(loan_grid, '$','Total Funded Amount', 'Total Amount Received', 'MTD Funded Amount', 'MTD Received Amount')
pctConverter(loan_grid, '%', 'Average Interest Rate', 'Average DTI')

In [105]:
loan_grid

,Loan Status,Total Loan Applicants,Total Funded Amount,Total Amount Received,Average Interest Rate,Average DTI,MTD Funded Amount,MTD Received Amount
0,Charged Off,5333,"$65,532,225.00","$37,284,763.00",0.14%,0.14%,"$8,732,775.00","$5,324,211.00"
1,Current,1098,"$18,866,500.00","$24,199,914.00",0.15%,0.15%,"$3,946,625.00","$4,934,318.00"
2,Fully Paid,32145,"$351,358,350.00","$411,586,256.00",0.12%,0.13%,"$41,302,025.00","$47,815,851.00"

## Analysis

### Monthly Trends by Issue Date

In [114]:
month_analysis = df.groupby(['Issue_Month', 'I_month_name']).agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'I_month_name': 'Month Name'})

# Replacing unwanted value
month_analysis.columns = month_analysis.columns.str.replace('_', ' ', regex=False)

# changing currency format
currencyConverter(month_analysis, '$', 'Total Funded Amount', 'Total Received Amount')

# displaying specific columns
month_analysis[['Month Name', 'Total Loan Applicants', 'Total Funded Amount', 'Total Received Amount']]

   Month Name  Total Loan Applicants Total Funded Amount Total Received Amount
0     January                   2332      $25,031,650.00        $27,578,836.00
1    February                   2279      $24,647,825.00        $27,717,745.00
2       March                   2627      $28,875,700.00        $32,264,400.00
3       April                   2755      $29,800,800.00        $32,495,533.00
4         May                   2911      $31,738,350.00        $33,750,523.00
5        June                   3184      $34,161,475.00        $36,164,533.00
6        July                   3366      $35,813,900.00        $38,827,220.00
7      August                   3441      $38,149,600.00        $42,682,218.00
8   September                   3536      $40,907,725.00        $43,983,948.00
9     October                   3796      $44,893,800.00        $49,399,567.00
10   November                   4035      $47,754,825.00        $50,132,030.00
11   December                   4314      $53,981,425.00        $58,074,380.00

### Regional Analysis

In [120]:
region_details = df.groupby('address_state').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'address_state': 'Address State'})

region_details.columns = region_details.columns.str.replace('_', ' ', regex=False)

currencyConverter(region_details, '$', 'Total Funded Amount', 'Total Received Amount')
region_details

,Address State,Total Loan Applicants,Total Funded Amount,Total Received Amount
0,AK,78,"$1,031,800.00","$1,108,570.00"
1,AL,432,"$4,949,225.00","$5,492,272.00"
2,AR,236,"$2,529,700.00","$2,777,875.00"
3,AZ,833,"$9,206,000.00","$10,041,986.00"
4,CA,6894,"$78,484,125.00","$83,901,234.00"
5,CO,770,"$8,976,000.00","$9,845,810.00"
6,CT,730,"$8,435,575.00","$9,357,612.00"
7,DC,214,"$2,652,350.00","$2,921,854.00"
8,DE,110,"$1,138,100.00","$1,269,136.00"
9,FL,2773,"$30,046,125.00","$31,601,905.00"
10,GA,1355,"$15,480,325.00","$16,728,040.00"
11,HI,170,"$1,850,525.00","$2,080,184.00"
12,IA,5,"$56,450.00","$64,482.00"
13,ID,6,"$59,750.00","$65,329.00"
14,IL,1486,"$17,124,225.00","$18,875,941.00"
15,IN,9,"$86,225.00","$85,521.00"
16,KS,260,"$2,872,325.00","$3,247,394.00"
17,KY,320,"$3,504,100.00","$3,792,530.00"
18,LA,426,"$4,498,900.00","$5,001,160.00"
19,MA,1310,"$15,051,000.00","$16,676,279.00"
20,MD,1027,"$11,911,400.00","$12,985,170.00"
21,ME,3,"$9,200.00","$10,808.00"
22,MI,685,"$7,829,900.00","$8,543,660.00"
23,MN,592,"$6,302,600.00","$6,750,746.00"
24,MO,660,"$7,151,175.00","$7,692,732.00"
25,MS,19,"$139,125.00","$149,342.00"
26,MT,79,"$829,525.00","$892,047.00"
27,NC,759,"$8,787,575.00","$9,534,813.00"
28,NE,5,"$31,700.00","$24,542.00"
29,NH,161,"$1,917,900.00","$2,101,386.00"
30,NJ,1822,"$21,657,475.00","$23,425,159.00"
31,NM,183,"$1,916,775.00","$2,084,485.00"
32,NV,482,"$5,307,375.00","$5,451,443.00"
33,NY,3701,"$42,077,050.00","$46,108,181.00"
34,OH,1188,"$12,991,375.00","$14,330,148.00"
35,OK,293,"$3,365,725.00","$3,712,649.00"
36,OR,436,"$4,720,150.00","$4,966,903.00"
37,PA,1482,"$15,826,525.00","$17,462,908.00"
38,RI,196,"$1,883,025.00","$2,001,774.00"
39,SC,464,"$5,080,475.00","$5,462,458.00"
40,SD,63,"$606,150.00","$656,514.00"
41,TN,17,"$162,175.00","$141,522.00"
42,TX,2664,"$31,236,650.00","$34,392,715.00"
43,UT,252,"$2,849,225.00","$2,952,412.00"
44,VA,1375,"$15,982,650.00","$17,711,443.00"
45,VT,54,"$504,100.00","$534,973.00"
46,WA,805,"$8,855,525.00","$9,531,739.00"
47,WI,446,"$5,070,450.00","$5,485,161.00"
48,WV,167,"$1,830,525.00","$1,991,936.00"
49,WY,79,"$890,750.00","$1,046,050.00"

### Loan Term Analysis

In [123]:
loan_term_details = df.groupby('term').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'term': 'Loan Term'})

loan_term_details.columns = loan_term_details.columns.str.replace('_', ' ', regex=False)

currencyConverter(loan_term_details, '$', 'Total Funded Amount', 'Total Received Amount')
loan_term_details

    Loan Term  Total Loan Applicants Total Funded Amount Total Received Amount
0   36 months                  28237     $273,041,225.00       $294,709,458.00
1   60 months                  10339     $162,715,850.00       $178,361,475.00

### Employee Length Analysis

In [125]:
emp_length_details = df.groupby('emp_length').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'emp_length': 'Employee Length'})

emp_length_details.columns = emp_length_details.columns.str.replace('_', ' ', regex=False)

currencyConverter(emp_length_details, '$', 'Total Funded Amount', 'Total Received Amount')
emp_length_details

,Employee Length,Total Loan Applicants,Total Funded Amount,Total Received Amount
0,1 year,3229,"$32,883,125.00","$35,498,348.00"
1,10+ years,8870,"$116,115,950.00","$125,871,616.00"
2,2 years,4382,"$44,967,975.00","$49,206,961.00"
3,3 years,4088,"$43,937,850.00","$47,551,832.00"
4,4 years,3428,"$37,600,375.00","$40,964,850.00"
5,5 years,3273,"$36,973,625.00","$40,397,571.00"
6,6 years,2228,"$25,612,650.00","$27,908,658.00"
7,7 years,1772,"$20,811,725.00","$22,584,136.00"
8,8 years,1476,"$17,558,950.00","$19,025,777.00"
9,9 years,1255,"$15,084,225.00","$16,516,173.00"
10,< 1 year,4575,"$44,210,625.00","$47,545,011.00"

### Loan Purpose Details

In [127]:
loan_purpose_details = df.groupby('purpose').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'purpose': 'Loan Purpose'})

loan_purpose_details.columns = loan_purpose_details.columns.str.replace('_', ' ', regex=False)

currencyConverter(loan_purpose_details, '$', 'Total Funded Amount', 'Total Received Amount')
loan_purpose_details

,Loan Purpose,Total Loan Applicants,Total Funded Amount,Total Received Amount
0,Debt consolidation,18214,"$232,459,675.00","$253,801,871.00"
1,car,1497,"$10,223,575.00","$11,324,914.00"
2,credit card,4998,"$58,885,175.00","$65,214,084.00"
3,educational,315,"$2,161,650.00","$2,248,380.00"
4,home improvement,2876,"$33,350,775.00","$36,380,930.00"
5,house,366,"$4,824,925.00","$5,185,538.00"
6,major purchase,2110,"$17,251,600.00","$18,676,927.00"
7,medical,667,"$5,533,225.00","$5,851,372.00"
8,moving,559,"$3,748,125.00","$3,999,899.00"
9,other,3824,"$31,155,750.00","$33,289,676.00"
10,renewable_energy,94,"$845,750.00","$898,931.00"
11,small business,1776,"$24,123,100.00","$23,814,817.00"
12,vacation,352,"$1,967,950.00","$2,116,738.00"
13,wedding,928,"$9,225,800.00","$10,266,856.00"

### Home Ownership Details

In [130]:
home_ownership_details = df.groupby('home_ownership').agg(
    Total_Loan_Applicants = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(columns = {'home_ownership': 'Home Ownership'})

home_ownership_details.columns = home_ownership_details.columns.str.replace('_', ' ', regex=False)

currencyConverter(home_ownership_details, '$', 'Total Funded Amount', 'Total Received Amount')
home_ownership_details

,Home Ownership,Total Loan Applicants,Total Funded Amount,Total Received Amount
0,MORTGAGE,17198,"$219,329,150.00","$238,474,438.00"
1,NONE,3,"$16,800.00","$19,053.00"
2,OTHER,98,"$1,044,975.00","$1,025,257.00"
3,OWN,2838,"$29,597,675.00","$31,729,129.00"
4,RENT,18439,"$185,768,475.00","$201,823,056.00"