# Hypothesis Testing

In [ ]:
'''
1 Year business
Average Profit = 500000 -> Sample

Total Sales = 1300000 -> Population

Types of Hypothesis Testing
-----------------
1. T Test
    a. One Sample T Test
    b. Two Sample T Test
2. ANOVA (Analysis of Variance) Test

3. Chi-Squared Test

- Statistics
- Probability

Stats -> (Actual mean - Sample mean) / (sd / root(total_number_of_data))

- If Stats value increases P-value decreases
- If stats value decreases P-value increases
'''

In [1]:
# Statistical calculation -> scipy -> scientific python
from scipy import stats
import pandas as pd

In [2]:
df = pd.read_csv('dataset/pizza_sales.csv')
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

## One Sample T Test

### Is the average total price of all pizza sales different from $15?

In [17]:
alpha = 0.05
sample = 15
population = df['total_price']

In [ ]:
'''
import numpy as np
actual_mean = population.mean()
sd = population.std()
total_data = np.sqrt(48619)

top_val = actual_mean - sample
bot_val = sd / total_data

top_val / bot_val
'''

In [21]:
# stats.ttest_1samp(population, popmean=sample)
t_statistics, p_value = stats.ttest_1samp(population, popmean=sample)

In [22]:
ho = f'The average total price of all pizza sales equals to ${sample}.'
ha = f'The average total price of all pizza sales is not equals to ${sample}.'
print(f'Ho: {ho}')
print(f'Ha: {ha}')

Ho: The average total price of all pizza sales equals to $15.
Ha: The average total price of all pizza sales is not equals to $15.

In [23]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis.\nConclusion: Needs to accept alternate hypothesis.\nHa: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis.\nConclusion: Needs to accept null hypothesis.\nHo: {ho}')

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
Ha: The average total price of all pizza sales is not equals to $15.

## Two sample T Test

### Is the average unit price of Classic Pizzas and Chicken Pizzas equal?

In [24]:
alpha = 0.05
classic_price = df[df['pizza_category'] == 'Classic']['unit_price']
chicken_price = df[df['pizza_category'] == 'Chicken']['unit_price']

In [28]:
# stats.ttest_ind(category1, category2, equal_var=True/False)
t_statistics, p_value = stats.ttest_ind(classic_price, chicken_price, equal_var=False)

In [29]:
ho = 'The average unit price of Classiic Pizzas and Chicken Pizzas are equal.'
ha = 'The average unit price of Classic Pizzas and Chicken Pizzas are not equal.'

print(f'Ho: {ho}')
print(f'Ha: {ha}')

Ho: The average unit price of Classiic Pizzas and Chicken Pizzas are equal.
Ha: The average unit price of Classic Pizzas and Chicken Pizzas are not equal.

In [32]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis.\nConclusion: Needs to accept alternate hypothesis.\nHa: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis.\nConclusion: Needs to accept null hypothesis.\nHo: {ho}')

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
Ha: The average unit price of Classic Pizzas and Chicken Pizzas are not equal.

## ANOVA Test (Analysis of Variance)

### Do the average total_price generated by all four pizza categories (Classic, Chicken, Supreme, and Veggie) differ significantly from one another?

In [33]:
alpha = 0.05
categories = ['Classic', 'Chicken', 'Supreme', 'Veggie']
grouped_prices = []

for category in categories:
    price = df[df['pizza_category'] == category]['total_price']
    grouped_prices.append(price)

In [36]:
t_statistics, p_value = stats.f_oneway(*grouped_prices)

In [41]:
pizza_price = df.groupby('pizza_category')['total_price'].mean().rename_axis('Pizza Category').rename(
    'Total Price'
).map("${:,.2f}".format).to_markdown(numalign='center', stralign='center')

In [44]:
ho = 'The average total price generated by all four pizza categories are equal to one another.'
ha = 'The average total price generated by all four pizza categories are not equal to one another.'

print(f'Ho: {ho}')
print(f'Ha: {ha}')
print('-'*36)
print(pizza_price)
print('-'*36)

Ho: The average total price generated by all four pizza categories are equal to one another.
Ha: The average total price generated by all four pizza categories are not equal to one another.
------------------------------------
|  Pizza Category  |  Total Price  |
|:----------------:|:-------------:|
|     Chicken      |    $18.12     |
|     Classic      |    $15.09     |
|     Supreme      |    $17.68     |
|      Veggie      |    $16.92     |
------------------------------------

In [38]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis.\nConclusion: Needs to accept alternate hypothesis.\nHa: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis.\nConclusion: Needs to accept null hypothesis.\nHo: {ho}')

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
Ha: The average total price generated by all four pizza categories are not equal to one another.

## Chi-Squared Test

### Is Pizza Category and Pizzz Size are dependent to one another?

In [4]:
alpha = 0.05
# contingency analysis -> crosstab (Cross Tabulation)
contingency = pd.crosstab(df['pizza_category'], df['pizza_size'])
contingency

pizza_size         L     M     S   XL  XXL
pizza_category
Chicken         4799  3811  2205    0    0
Classic         3987  4045  5975  544   28
Supreme         4477  3977  3323    0    0
Veggie          5263  3552  2634    0    0

In [7]:
# dof = (number of rows - 1) * (number of columns - 1)
# dof = (4 - 1) * (5 - 1)
# dof

In [8]:
t_statistics, p_value, dof, ef = stats.chi2_contingency(contingency)

In [9]:
ho = 'Pizza Category and Pizza size are dependent to one other.'
ha = 'Pizza Category and Pizza size are independent to one other.'

print(f'Ho: {ho}')
print(f'Ha: {ha}')

Ho: Pizza Category and Pizza size are dependent to one other.
Ha: Pizza Category and Pizza size are independent to one other.

In [10]:
if p_value < alpha:
    print(f'Decision: Failed to accept null hypothesis.\nConclusion: Needs to accept alternate hypothesis.\nHa: {ha}')
else:
    print(f'Decision: Failed to reject null hypothesis.\nConclusion: Needs to accept null hypothesis.\nHo: {ho}')

Decision: Failed to accept null hypothesis.
Conclusion: Needs to accept alternate hypothesis.
Ha: Pizza Category and Pizza size are independent to one other.